//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DairyManagement.Models.LocalDBEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMilkInfo
    {
        public int Id { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> MilkTypeId { get; set; }
        public Nullable<decimal> MilkValue { get; set; }
        public Nullable<decimal> FatValue { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual MilkType MilkType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual VendorInfo VendorInfo { get; set; }
    }
}
